apiVersion: v1
kind: Service
metadata:
  name: go-my-storage
  namespace: my-storage
  labels:
    app: go-my-storage
spec:
  selector:
    app: go-my-storage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
